<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.3.0" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="10.3.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YANEDGE.EmailManagement.Application.Contracts\YANEDGE.EmailManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\YANEDGE.EmailManagement.Domain\YANEDGE.EmailManagement.Domain.csproj" />
  </ItemGroup>

</Project>
